#!/bin/sh
# D<digit><digit><whatever-else-you-want> is executed before
#  unpacking the source inside the chroot, after setting up the
#  chroot environment. Create $TMP, and $TMPDIR if necessary.
#
# This is called before build-dependency is satisfied. 
# Also useful for calling apt-get update

set -ex

mkdir -p /usr/include/libyuv
[ -h /usr/include/libyuv/libyuv.h ] || ln -sf /usr/include/libyuv.h /usr/include/libyuv/libyuv.h
