#!/bin/sh
# Fix ldconfig

echo "I: Fix ldconfig to never fail"
cat <<EOF > /sbin/ldconfig
#!/bin/sh

if  test \$# = 0							\\
    && test x"\$LDCONFIG_NOTRIGGER" = x				\\
 && test x"\$DPKG_MAINTSCRIPT_PACKAGE" != x			\\
 && dpkg-trigger --check-supported 2>/dev/null			\\
 && dpkg --compare-versions "\$DPKG_RUNNING_VERSION" ge '1.14.5ubuntu10~~'
then
	if dpkg-trigger --no-await ldconfig; then
		if test x"\$LDCONFIG_TRIGGER_DEBUG" != x; then
			echo "ldconfig: wrapper deferring update (trigger activated)"
		fi
		exit 0
	fi	
fi

/sbin/ldconfig.real "\$@"
exit 0
EOF
chmod 755 /sbin/ldconfig


